-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-verbose
-optimizationpasses 5
-overloadaggressively
-repackageclasses ''
-allowaccessmodification
-mergeinterfacesaggressively
-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.jni.** { *; }
-keep class * implements com.facebook.react.bridge.NativeModule { *; }
-keep class * implements com.facebook.react.bridge.ReactContextBaseJavaModule { *; }
-keep class expo.modules.core.interfaces.services.KeepAwakeManager { *; }
-keep class expo.modules.kotlin.types.AnyTypeProvider { *; }
-keep class expo.modules.kotlin.types.LazyKType { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
